# Generated by Django 5.0.3 on 2024-03-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_type_of_cut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofcut',
            name='value',
            field=models.FloatField(),
        ),
    ]
