# Generated by Django 5.0.3 on 2024-04-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_schedule_day_remove_schedule_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeofcut',
            old_name='type',
            new_name='type_cut',
        ),
    ]
