# Generated by Django 5.0.3 on 2024-05-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_schedule_conclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='conclude',
            field=models.BooleanField(default=False),
        ),
    ]
