# Generated by Django 5.0.3 on 2024-05-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_schedule_conclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date_hour',
            field=models.DateTimeField(null=True, unique=True),
        ),
    ]
